-- Base de conocimiento para chatbot SWO
SET NAMES utf8mb4;
USE swo_db;

INSERT INTO chatbot_conocimiento (categoria, palabras_clave, pregunta, respuesta, pasos, nivel_soporte) VALUES

-- CONTRASEÑAS
('Contraseñas','contrasena,contraseña,password,clave,restablecer,cambiar,olvide,reset,actualizar','¿Cómo cambio o restablezco mi contraseña?','Para cambiar o restablecer la contraseña sigue los pasos indicados. Recuerda usar al menos 8 caracteres, una mayúscula, un número y un carácter especial.','1. Ve al panel de administración de usuarios.||2. Busca el usuario afectado por nombre o correo.||3. Haz clic en Editar usuario.||4. Ingresa la nueva contraseña en el campo correspondiente.||5. Guarda los cambios.||6. Notifica al usuario su nueva contraseña por un canal seguro.',1),

('Contraseñas','caducó,caduco,expiró,expiro,expirada,vencida,vencio','Mi contraseña caducó y no puedo ingresar.','Las contraseñas vencen según la política de seguridad. Un administrador debe restablecerla desde Gestión de Usuarios.','1. Contacta al administrador de sistemas.||2. Proporciona tu correo institucional.||3. El administrador generará una contraseña temporal.||4. Ingresa con la contraseña temporal.||5. Cámbiala de inmediato en la sección Mi perfil.',1),

('Contraseñas','bloqueado,bloqueo,intentos,demasiados intentos,cuenta bloqueada','Mi cuenta está bloqueada por intentos fallidos.','La cuenta se bloquea tras 5 intentos fallidos como medida de seguridad. Para desbloquearla se requiere intervención de un administrador.','1. Espera 30 minutos para el desbloqueo automático.||2. Si el bloqueo persiste, contacta soporte.||3. Soporte verificará tu identidad.||4. Se restablecerá el acceso con una contraseña temporal.||5. Se registrará el incidente en bitácora.',1),

-- RED Y CONECTIVIDAD
('Red y Conectividad','internet,no conecta,sin internet,conexion,red,wifi,cable,acceso red','No tengo acceso a internet o a la red corporativa.','Los problemas de conectividad pueden tener varias causas. Sigue el diagnóstico básico antes de escalar.','1. Verifica que el cable de red esté conectado firmemente.||2. Reinicia el adaptador: cmd como admin → ipconfig /release y luego ipconfig /renew.||3. Reinicia el router o switch más cercano.||4. Comprueba si otros equipos tienen el mismo problema.||5. Si es generalizado, escala a Infraestructura.||6. Si es solo tu equipo, revisa los controladores de la tarjeta de red.',1),

('Red y Conectividad','vpn,vpn no conecta,red privada,acceso remoto','El cliente VPN no conecta.','Los fallos de VPN pueden deberse a credenciales incorrectas, certificados vencidos o problemas en el servidor VPN.','1. Verifica que tu usuario y contraseña de VPN sean correctos.||2. Comprueba la fecha y hora del sistema; una hora incorrecta invalida certificados.||3. Reinicia el servicio VPN desde Panel de control > Servicios.||4. Desinstala y reinstala el cliente VPN.||5. Si el certificado está vencido, contacta al administrador de seguridad.',2),

('Red y Conectividad','lento,lenta,velocidad,latencia,ping,timeout,latencia alta','La red está muy lenta o hay alta latencia.','La lentitud puede deberse a saturación del ancho de banda, problemas de hardware o mala configuración.','1. Ejecuta ping -t 8.8.8.8 y observa la latencia.||2. Cierra aplicaciones que consuman mucho ancho de banda.||3. Verifica si hay actualizaciones masivas en segundo plano.||4. Reporta a Infraestructura con los resultados del ping.||5. El equipo de redes revisará el tráfico con herramientas de monitoreo.',2),

('Red y Conectividad','ip,direccion ip,ip duplicada,conflicto ip','Conflicto de dirección IP detectado.','Dos dispositivos tienen la misma IP, causando intermitencia en la red.','1. Abre cmd como administrador.||2. Ejecuta: ipconfig /release.||3. Ejecuta: ipconfig /flushdns.||4. Ejecuta: ipconfig /renew.||5. Si persiste, configura la IP como automática (DHCP) en propiedades de red.||6. El admin de red debe revisar la tabla DHCP.',1),

-- CORREO ELECTRONICO
('Correo Electronico','correo,email,outlook,no envia,no recibe,buzon,correo no funciona','El correo electrónico no funciona o no envía/recibe mensajes.','Los problemas de correo pueden estar relacionados con el cliente, el servidor o la cuota superada.','1. Verifica conexión a internet.||2. Comprueba si el servidor de correo está operativo.||3. Revisa si la bandeja de entrada está llena (cuota).||4. En Outlook: Archivo > Configuración de la cuenta > Prueba de configuración.||5. Elimina correos grandes de Enviados y Papelera.||6. Si usa Outlook, repara el perfil desde Panel de control > Correo.',1),

('Correo Electronico','spam,phishing,suplantacion,correo sospechoso','Recibí un correo sospechoso o de phishing.','El phishing intenta obtener datos confidenciales. No hagas clic en enlaces ni descargues adjuntos de remitentes desconocidos.','1. NO hagas clic en ningún enlace del correo.||2. NO descargues archivos adjuntos.||3. Marca el correo como spam en tu cliente.||4. Reporta el intento al equipo de Seguridad.||5. Si ya hiciste clic, cambia tu contraseña de inmediato.||6. El equipo de Seguridad realizará un análisis de amenazas.',2),

-- APLICACIONES
('Aplicaciones','aplicacion,programa,no abre,no inicia,crashea,cierra,error al abrir','Una aplicación no abre o se cierra inesperadamente.','Los fallos de aplicaciones pueden deberse a archivos dañados, falta de memoria o conflictos de software.','1. Cierra la aplicación desde el Administrador de tareas.||2. Reinicia el equipo.||3. Verifica que la aplicación esté actualizada.||4. Repara la instalación: Panel de control > Programas > app > Reparar.||5. Revisa el Visor de sucesos: Registros de Windows > Aplicación.||6. Si persiste, desinstala y reinstala la aplicación.',1),

('Aplicaciones','actualizacion,update,version,parche,actualizar software','¿Cómo actualizo una aplicación o el sistema?','Las actualizaciones deben coordinarse con TI en entornos corporativos.','1. Verifica que la actualización haya sido aprobada por TI.||2. Haz una copia de seguridad antes de actualizar.||3. Para Windows: Inicio > Configuración > Windows Update.||4. Para aplicaciones de negocio, contacta al administrador.||5. Programa actualizaciones en horarios de baja actividad.',2),

('Aplicaciones','licencia,expiró licencia,activacion,clave de producto','La licencia de una aplicación expiró.','Las licencias corporativas son gestionadas por TI. No intentes activar software por tu propia cuenta.','1. Identifica el software y versión afectados.||2. Crea un ticket con el nombre del software y código de error.||3. TI verificará el estado de la licencia.||4. Si es renovación, Compras coordinará con el proveedor.||5. Se instalará la nueva licencia en máximo 2 días hábiles.',2),

-- HARDWARE
('Hardware','computador,computadora,pc,equipo,no enciende,no prende,pantalla negra,no arranca','El computador no enciende o muestra pantalla negra.','Los problemas de arranque pueden ser de hardware, actualizaciones o software.','1. Verifica que el equipo esté conectado a la corriente.||2. Presiona el botón de encendido 10 segundos para forzar apagado, luego enciéndelo.||3. Conecta un monitor externo para descartar falla del panel.||4. Intenta arrancar en Modo Seguro (F8 al iniciar).||5. Si hay pitidos al encender, documenta cuántos y escala a soporte de hardware.',2),

('Hardware','impresora,imprimir,no imprime,cola de impresion,papel atascado','La impresora no imprime o tiene un atasco de papel.','Los problemas de impresión suelen resolverse limpiando la cola y reiniciando el servicio.','1. Cancela todos los trabajos en cola de impresión.||2. Reinicia el servicio: Servicios > Cola de impresión > Reiniciar.||3. Si hay papel atascado, ábrela y retíralo con cuidado.||4. Verifica que el cartucho/tóner tenga tinta.||5. Reinstala el controlador desde el sitio oficial del fabricante.',1),

('Hardware','disco duro,ssd,espacio,almacenamiento,lleno,sin espacio','El disco está lleno o sin espacio disponible.','Un disco lleno causa lentitud extrema e impide guardar archivos.','1. Ejecuta el Liberador de espacio en disco (Limpieza de disco).||2. Vacía la Papelera de reciclaje.||3. Elimina archivos temporales: ejecuta %temp% en Ejecutar.||4. Mueve archivos grandes a la nube o unidad externa.||5. Desinstala programas que no uses.||6. Si el disco supera el 90%, solicita upgrade de almacenamiento.',1),

('Hardware','pantalla,monitor,resolucion,parpadea,distorsion','La pantalla parpadea o tiene distorsión de imagen.','Los problemas de pantalla pueden ser por cables dañados, controladores o fallas de hardware.','1. Verifica que el cable de video esté bien conectado.||2. Actualiza los controladores de la tarjeta gráfica.||3. Cambia la tasa de refresco: clic derecho > Configuración de pantalla > Avanzada.||4. Prueba con otro monitor para aislar el fallo.||5. Si persiste, escala a soporte de hardware.',2),

('Hardware','teclado,mouse,raton,no funciona teclado,no funciona mouse,periferico','El teclado o mouse no funciona.','Los periféricos fallan por controladores, puertos USB o daño físico.','1. Desconecta y vuelve a conectar el dispositivo.||2. Prueba en otro puerto USB.||3. Limpia el dispositivo; si es inalámbrico revisa las pilas.||4. En Administrador de dispositivos verifica si hay errores.||5. Actualiza o reinstala los controladores.||6. Si es rotura física, solicita reposición a TI.',1),

-- SEGURIDAD
('Seguridad','virus,malware,antivirus,infectado,ransomware,amenaza','Creo que mi equipo tiene un virus o malware.','Un equipo infectado puede comprometer toda la empresa. Actúa de inmediato.','1. DESCONECTA el equipo de la red inmediatamente.||2. NO apagues el equipo para preservar evidencia.||3. Llama al equipo de Seguridad de inmediato.||4. No copies archivos a otros dispositivos.||5. El equipo realizará un análisis forense.||6. El equipo quedará en cuarentena hasta su limpieza completa.',3),

('Seguridad','acceso no autorizado,hackeo,hackeado,brecha,robo contrasena','Creo que mi cuenta fue hackeada o accedida sin autorización.','Un acceso no autorizado es un incidente crítico de seguridad.','1. Cambia tu contraseña de inmediato.||2. Revisa los accesos recientes de tu cuenta.||3. Reporta el incidente al equipo de Seguridad.||4. Revisa si hay correos enviados que no recuerdas o reglas extrañas.||5. Seguridad auditará los logs de acceso.||6. Activa autenticación de dos factores.',3),

('Seguridad','permiso,acceso denegado,sin permiso,no tengo acceso,carpeta restringida','No tengo permiso para acceder a una carpeta o recurso.','Los accesos son controlados por el administrador según rol y área.','1. Verifica que el recurso corresponde a tu área de trabajo.||2. Solicita acceso a través de un ticket: indica recurso, justificación y aprobador.||3. Tu jefe directo debe aprobar la solicitud.||4. TI asignará el permiso en máximo 1 día hábil.||5. El acceso otorgado quedará documentado en bitácora.',1),

-- SISTEMA OPERATIVO
('Sistema Operativo','windows,actualizacion windows,windows update,error windows','Windows tiene un error o no actualiza correctamente.','Los errores de Windows Update pueden deberse a archivos dañados o conflictos de software.','1. Ejecuta el solucionador de problemas de Windows Update.||2. Abre CMD como admin y ejecuta: sfc /scannow.||3. Ejecuta: DISM /Online /Cleanup-Image /RestoreHealth.||4. Reinicia el servicio Windows Update desde services.msc.||5. Si persiste tras 3 intentos, escala a nivel 2.',2),

('Sistema Operativo','pantalla azul,bsod,error critico,volcado,dump','Aparece pantalla azul (BSOD) o error crítico del sistema.','La pantalla azul indica un error grave de hardware, controladores o software incompatible.','1. Anota el código de error que aparece (ej: MEMORY_MANAGEMENT).||2. Reinicia el equipo y verifica si se repite.||3. Arranca en Modo Seguro para diagnosticar.||4. Actualiza todos los controladores, especialmente video y red.||5. Ejecuta diagnóstico de memoria: mdsched.exe.||6. Escala a nivel 2 con el código de error documentado.',2),

('Sistema Operativo','lento,rendimiento,procesador,memoria ram,cpu,100 porciento','El equipo está muy lento o el procesador al 100%.','El rendimiento bajo puede deberse a exceso de procesos, malware o hardware insuficiente.','1. Abre Administrador de tareas (Ctrl+Shift+Esc) e identifica procesos que consumen CPU/RAM.||2. Finaliza procesos desconocidos con cuidado.||3. Desactiva programas de inicio innecesarios.||4. Ejecuta un análisis completo de antivirus.||5. Si el equipo tiene más de 5 años con menos de 4GB RAM, solicita evaluación de hardware.',2),

-- BACKUP Y RECUPERACIÓN
('Backup y Recuperacion','backup,respaldo,recuperar archivo,archivo perdido,borre,elimine','Borré un archivo importante o necesito recuperarlo.','La recuperación depende del sistema de backup configurado.','1. Revisa la Papelera de reciclaje primero.||2. Clic derecho sobre la carpeta > Restaurar versiones anteriores.||3. Busca en OneDrive/SharePoint si usas nube.||4. Solicita recuperación desde backup a TI: nombre, carpeta y fecha aproximada.||5. TI intentará recuperarlo desde el último backup.',1),

('Backup y Recuperacion','backup fallido,respaldo fallido,copia seguridad,error backup','El sistema de backup reporta un error.','Los fallos de backup son alertas críticas que deben atenderse el mismo día.','1. Revisa el log de la herramienta de backup para identificar el error.||2. Verifica que el servidor de backup tenga espacio suficiente.||3. Comprueba la conectividad entre el servidor de backup y el origen.||4. Reintenta el backup manualmente.||5. Escala a nivel 2 si el fallo se repite.',2),

-- SERVIDORES Y SERVICIOS
('Servidores','servidor,service,servicio,caido,no disponible,fuera de linea','Un servidor o servicio está caído o no disponible.','La caída de un servidor es un incidente de alta prioridad. Activa el protocolo de respuesta inmediata.','1. Verifica desde otro equipo si el servicio es inaccesible.||2. Revisa el panel de monitoreo de servidores.||3. Ejecuta ping nombre-servidor para probar conectividad.||4. Notifica al administrador de servidores de inmediato.||5. Activa el protocolo de contingencia si está definido.||6. Documenta hora exacta, servicios afectados y usuarios impactados.',3),

('Servidores','base de datos,sql,mysql,oracle,conexion bd,no conecta bd','No puedo conectarme a la base de datos.','Los problemas de conexión a BD pueden deberse al servicio detenido, credenciales incorrectas o firewall.','1. Verifica si el servicio de BD está activo en el servidor.||2. Comprueba las credenciales de conexión.||3. Verifica la cadena de conexión en el archivo de configuración.||4. Revisa el firewall; el puerto de BD debe estar abierto.||5. Revisa los logs del motor de base de datos.||6. Escala al DBA si el servicio está caído.',2),

-- USUARIOS Y CUENTAS
('Usuarios y Cuentas','crear usuario,nuevo usuario,alta usuario,cuenta nueva','¿Cómo se crea un nuevo usuario en el sistema?','La creación de usuarios está restringida al administrador para garantizar la seguridad.','1. Ve a Gestión de Usuarios en el panel de administración.||2. Haz clic en Nuevo Usuario.||3. Completa: nombre completo, correo, rol, departamento y proyecto.||4. Define una contraseña inicial segura.||5. Notifica al nuevo usuario sus credenciales por canal seguro.||6. El usuario debe cambiar la contraseña en su primer ingreso.',1),

('Usuarios y Cuentas','eliminar usuario,baja usuario,desactivar cuenta','¿Cómo se elimina o desactiva un usuario?','La eliminación es lógica (datos históricos se mantienen) para preservar la trazabilidad.','1. Ve a Gestión de Usuarios.||2. Busca el usuario a eliminar.||3. Haz clic en Eliminar o Desactivar.||4. El usuario quedará inactivo y no podrá ingresar.||5. Sus incidencias históricas se conservan.||6. Documenta el motivo de la baja en el ticket de solicitud.',1),

('Usuarios y Cuentas','rol,permisos,cambiar rol,asignar rol','¿Cómo cambio el rol o permisos de un usuario?','Los roles determinan las acciones de cada usuario en la plataforma.','1. Ve a Gestión de Usuarios.||2. Selecciona el usuario.||3. En el modal de edición, modifica el campo Rol.||4. Roles disponibles: Administrador, Analista, Desarrollador, Mesa de Servicio, Soporte, Jefe.||5. Guarda los cambios.||6. El cambio aplica en el próximo inicio de sesión.',1),

-- INCIDENCIAS
('Incidencias','crear incidencia,nueva incidencia,abrir ticket,registrar incidente','¿Cómo creo una nueva incidencia?','Las incidencias se registran en el panel de Incidentes para su seguimiento.','1. Ve a la sección Incidencias.||2. Haz clic en Nueva Incidencia.||3. Completa: Título descriptivo, Descripción del problema, Estado (Abierto), Impacto (Bajo/Medio/Alto/Crítico) y Ubicación.||4. Haz clic en Guardar Incidencia.||5. Se asignará un ID y quedará registrada.||6. Recibirás notificaciones sobre el avance.',1),

('Incidencias','prioridad,prioritario,urgente,critico,sla,tiempo respuesta','¿Qué niveles de prioridad existen y cuáles son los SLA?','Los SLA definen los tiempos máximos de respuesta según la prioridad del incidente.','Niveles disponibles:\n- Critico: respuesta 1 hora, resolución 4 horas.\n- Alta: respuesta 2 horas, resolución 8 horas.\n- Media: respuesta 4 horas, resolución 24 horas.\n- Baja: respuesta 8 horas, resolución 72 horas.',1),

('Incidencias','cerrar incidencia,resolver,cerrar ticket,estado resuelto','¿Cómo cierro o resuelvo una incidencia?','El cierre documenta la solución aplicada y calcula el cumplimiento del SLA.','1. Abre la incidencia desde el panel de Incidentes.||2. En el campo Estado, selecciona Resuelto o Cerrado.||3. Documenta la solución en los comentarios.||4. Actualiza la ubicación si cambió.||5. Guarda los cambios.||6. El sistema registrará la fecha y hora para el cálculo de SLA.',1),

('Incidencias','escalar,escalamiento,nivel 2,segundo nivel,asignar a otro','¿Cómo escalo una incidencia a un nivel superior?','El escalamiento se usa cuando el nivel 1 no puede resolver el problema en el tiempo establecido.','1. Verifica que se hayan agotado los procedimientos de nivel 1.||2. Cambia el estado a En Escalamiento.||3. Documenta en los comentarios qué se intentó y cuál es el bloqueo.||4. Asigna la incidencia al analista de nivel 2 o especialista.||5. Notifica al supervisor y al usuario afectado sobre el escalamiento.',2),

-- OFFICE Y HERRAMIENTAS
('Office y Herramientas','excel,word,powerpoint,office no abre,office error','Microsoft Office presenta errores o no abre.','Los problemas de Office pueden resolverse con la herramienta de reparación integrada.','1. Cierra todas las aplicaciones de Office.||2. Panel de Control > Programas > Microsoft Office > Cambiar > Reparación rápida.||3. Si la reparación rápida no funciona, selecciona Reparación en línea.||4. Reinicia el equipo.||5. Verifica que tu licencia de Office esté activa.||6. Si persiste, escala a soporte de aplicaciones.',1),

('Office y Herramientas','excel no guarda,archivo bloqueado,en uso,otra persona tiene abierto','Archivo de Excel o Word está bloqueado o en uso.','Los archivos compartidos pueden quedar bloqueados si alguien los tiene abierto o hubo un cierre inesperado.','1. Verifica con tu equipo si alguien más tiene el archivo abierto.||2. Busca y elimina el archivo de bloqueo (comienza con ~ en la misma carpeta).||3. Si está en SharePoint, ve a la biblioteca y desprotege el archivo.||4. Si nadie lo tiene abierto, reinicia el servicio de red.',1),

-- SOPORTE REMOTO
('Soporte Remoto','soporte remoto,acceso remoto,teamviewer,anydesk,escritorio remoto,rdp','Necesito soporte remoto o acceso a mi equipo remotamente.','El soporte remoto debe ser autorizado y documentado para garantizar la seguridad.','1. Solicita el soporte remoto a través de un ticket.||2. El técnico iniciará la sesión con tu autorización explícita.||3. Nunca compartas tu contraseña; el técnico usa herramientas seguras.||4. Supervisa todas las acciones durante la sesión.||5. Al finalizar, el técnico cerrará la sesión y podrás verificar los cambios.',1),

-- PLATAFORMA SWO
('Plataforma SWO','plataforma,sistema,swo,servicedesk,helpdesk,modulos','¿Qué módulos tiene la plataforma SWO ServiceDesk?','SWO ServiceDesk es la plataforma integral de gestión de incidencias de la organización.','Módulos disponibles:\n- Panel Principal: resumen de actividad y estadísticas.\n- Incidencias: registro y seguimiento de incidentes.\n- Usuarios: gestión de cuentas (solo Administrador).\n- Proyectos: gestión de proyectos (solo Administrador).\n- Reportes: estadísticas y exportación a Excel.\n- ChatBot: asistente de soporte con base de conocimiento.',1),

('Plataforma SWO','reporte,exportar,excel,descargar incidencias','¿Cómo genero y descargo un reporte de incidencias?','Los reportes se generan desde el módulo de Reportes y se descargan en formato CSV compatible con Excel.','1. Ve a la sección Reportes en el menú lateral.||2. Haz clic en Exportar Excel o Descargar Excel.||3. El sistema obtiene todas las incidencias de la base de datos.||4. Se descarga automáticamente un archivo .csv.||5. El reporte queda registrado en el historial.||6. Abre el CSV con Excel usando codificación UTF-8 si los caracteres no se ven bien.',1),

-- ACTIVE DIRECTORY
('Active Directory','active directory,directorio activo,ad,grupo ad,politica,gpo,dominio','¿Cómo gestiono usuarios en Active Directory?','Active Directory gestiona identidades y políticas en entornos Windows corporativos.','1. Abre Usuarios y equipos de Active Directory (dsa.msc).||2. Para crear usuario: clic derecho sobre la OU > Nuevo > Usuario.||3. Para restablecer contraseña: clic derecho sobre el usuario > Restablecer contraseña.||4. Para agregar a un grupo: propiedades del usuario > pestaña Miembro de.||5. Los cambios de GPO tardan hasta 90 minutos en propagarse o ejecuta: gpupdate /force.',2),

-- IMPRESORAS DE RED
('Hardware','impresora de red,network printer,impresora compartida,agregar impresora','¿Cómo agrego o configuro una impresora de red?','Las impresoras de red se agregan mediante la IP del dispositivo o el nombre del servidor de impresión.','1. Ve a Dispositivos e impresoras > Agregar una impresora.||2. Selecciona La impresora que quiero no está en la lista.||3. Elige Agregar una impresora usando una dirección TCP/IP.||4. Ingresa la IP de la impresora.||5. Instala el controlador correspondiente.||6. Define si será la impresora predeterminada.',1),

-- CERTIFICADOS
('Seguridad','certificado,certificado digital,certificado ssl,certificado vencido,https error','El certificado de seguridad de un sitio está vencido o da error.','Los errores de certificado indican que la conexión puede no ser segura.','1. Verifica la fecha de vencimiento del certificado haciendo clic en el candado del navegador.||2. Si es un certificado interno, contacta al administrador para renovarlo.||3. No agregues excepciones de seguridad permanentes sin autorización de TI.||4. Si es un sitio externo importante, reporta el problema al proveedor.||5. Escala a nivel 2 para renovación de certificados de infraestructura.',2),

-- TELEFONOS IP
('Comunicaciones','telefono ip,voip,no escucha,no se escucha,calidad llamada,extension','El teléfono IP tiene problemas de audio o no funciona.','Los problemas de telefonía IP pueden ser de red, configuración o hardware del dispositivo.','1. Reinicia el teléfono IP desconectando el cable de alimentación o PoE.||2. Verifica la calidad de la red con un ping al servidor de telefonía.||3. Comprueba que el cable de red del teléfono esté correctamente conectado.||4. Revisa el estado de la extensión en la consola de administración de telefonía.||5. Si el problema persiste, escala al administrador de comunicaciones.',2),

-- NUBE Y ALMACENAMIENTO
('Nube y Almacenamiento','onedrive,sharepoint,nube,sincronizar,no sincroniza,google drive','OneDrive o SharePoint no sincroniza archivos.','Los problemas de sincronización pueden deberse a conflictos de archivos, falta de espacio o credenciales.','1. Haz clic en el icono de OneDrive en la barra de tareas.||2. Verifica si hay errores o conflictos de sincronización.||3. Pausa y reanuda la sincronización.||4. Cierra sesión en OneDrive y vuelve a iniciarla.||5. Verifica que tu cuota de almacenamiento no esté llena.||6. Si el problema persiste, desinstala y reinstala el cliente de OneDrive.',1);

SELECT CONCAT('Total registros en chatbot_conocimiento: ', COUNT(*)) AS resultado FROM chatbot_conocimiento;
